title: ArkOS-R5XS
description: Community Maintained Image of ArkOS for the Game Console R5XS, Might also work with the Powkiddy RGB10MAX/2.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
